---
- name: "Create user for ansible"
  hosts: service.backup 

  become: true
  vars: 
    sudo_user: ans
  gather_facts: yes

  tasks:
    - name: Add {{ sudo_user }} user
      become: true
      user:
        name: "{{ sudo_user }}"
        groups: sudo
        append: true
        state: present
        createhome: true

    - name: Make sudo without password for {{ sudo_user }} user
      become: true
      copy:
        dest: /etc/sudoers.d/80-ansible-sudo-user
        content: "{{ sudo_user }} ALL=(ALL) NOPASSWD:ALL"
        mode: 0440

    - name: "Create .ssh directory"
      file:
        path: /home/{{ sudo_user }}/.ssh
        state: directory
        owner: "{{ sudo_user }}"
        group: "{{ sudo_user }}" 
        mode: 0700

    - name: "copy pub key"
      copy:
        src: files/id_ed25519.pub
        dest: /home/{{ sudo_user }}/.ssh/authorized_keys
        mode: 0700
        owner: "{{ sudo_user }}"
        group: "{{ sudo_user }}"
...
